// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIjW4vXCUUzCEZsxzGjnVopGoKjitLBNY',
    appId: '1:627643144536:web:27e7260ca31beded9b2d2d',
    messagingSenderId: '627643144536',
    projectId: 'vision-go-b1cda',
    authDomain: 'vision-go-b1cda.firebaseapp.com',
    databaseURL: 'https://vision-go-b1cda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vision-go-b1cda.firebasestorage.app',
    measurementId: 'G-6XGN5CKHP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOVZVg9RTk_MKq_-j8sSM8ViJ0lhX0L-c',
    appId: '1:627643144536:android:16e48b24818377e69b2d2d',
    messagingSenderId: '627643144536',
    projectId: 'vision-go-b1cda',
    databaseURL: 'https://vision-go-b1cda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vision-go-b1cda.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA12DUE-b5WGZ6Ac9ImrK-Xn3GayOvhBYI',
    appId: '1:627643144536:ios:6ccd51cf40ac3fdd9b2d2d',
    messagingSenderId: '627643144536',
    projectId: 'vision-go-b1cda',
    databaseURL: 'https://vision-go-b1cda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vision-go-b1cda.firebasestorage.app',
    iosBundleId: 'com.example.objectDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA12DUE-b5WGZ6Ac9ImrK-Xn3GayOvhBYI',
    appId: '1:627643144536:ios:6ccd51cf40ac3fdd9b2d2d',
    messagingSenderId: '627643144536',
    projectId: 'vision-go-b1cda',
    databaseURL: 'https://vision-go-b1cda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vision-go-b1cda.firebasestorage.app',
    iosBundleId: 'com.example.objectDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIjW4vXCUUzCEZsxzGjnVopGoKjitLBNY',
    appId: '1:627643144536:web:35df0aeeba9968419b2d2d',
    messagingSenderId: '627643144536',
    projectId: 'vision-go-b1cda',
    authDomain: 'vision-go-b1cda.firebaseapp.com',
    databaseURL: 'https://vision-go-b1cda-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vision-go-b1cda.firebasestorage.app',
    measurementId: 'G-B7401BG55W',
  );
}
